
# Name your project! Project names should be lowercase and use underscores as separators
# See documentation: https://docs.getdbt.com/docs/build/projects

name: 'llm_data_transforms'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'llm_data_transforms'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  llm_data_transforms:
    staging:
      +materialized: table
    marts:
      +materialized: table
