llm_data_transforms:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'postgres') }}"
      port: "{{ env_var('DB_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('DB_NAME', 'llm_data') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0

  target: dev
